import { fileURLToPath } from 'node:url'
import { withCheckDigit } from './ean13'

/** The barcode painted into the fake camera feed, shared by setup and the specs. */
export const FAKE_CAMERA_CODE = withCheckDigit('859400102030')

/** Generated by global-setup before Chromium launches; gitignored. */
export const FAKE_CAMERA_Y4M = fileURLToPath(new URL('../.playwright/barcode.y4m', import.meta.url))
