/**
 * Subsets Roboto to the characters a handover protocol can contain, then records
 * exactly which characters survived so the app can guard against the rest.
 *
 * Run once with `npm run font:subset`; the outputs (public/fonts/*.ttf and
 * src/lib/charset.json) are committed. Source TTFs live in assets/fonts-src/ so
 * this reproduces offline forever.
 *
 * Two things here are load-bearing:
 *
 * 1. Bold is not optional. jsPDF-autotable renders table headers bold, and with no
 *    bold face registered jsPDF silently falls back to Helvetica and mangles the
 *    header instead of throwing.
 *
 * 2. The charset must cover more than Czech. Product names in a Czech warehouse are
 *    routinely German or Slovak (Müsli, Jägermeister, ľalia), and jsPDF's handling of
 *    a character its font lacks is catastrophic and silent: it either drops the
 *    character or truncates the entire string from that point on. Measured:
 *      "Müsli tyčinka ořechová" -> "M"
 *      "Slovenská ľalia ôsma"   -> "Slovenská alia"
 *    So we cover all of Latin-1 + Latin Extended-A, and pdf.ts screens whatever is
 *    still missing against charset.json rather than letting a name vanish.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import subsetFont from 'subset-font'
import { create as createFont } from 'fontkit'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'assets', 'fonts-src')
const OUT = join(ROOT, 'public', 'fonts')
const CHARSET_JSON = join(ROOT, 'src', 'lib', 'charset.json')

const range = (from, to) =>
  Array.from({ length: to - from + 1 }, (_, i) => String.fromCodePoint(from + i)).join('')

const REQUESTED = [
  range(0x20, 0x7e), // ASCII printable
  range(0xa0, 0xff), // Latin-1 Supplement — German, French, Spanish, Nordic
  range(0x100, 0x17f), // Latin Extended-A — Czech, Slovak, Polish, Hungarian, Baltic
  '‐‑‒–—―', // dashes
  '‘’‚‛“”„‟', // quotes, incl. Czech „ “
  '†‡•…‰€™', // misc punctuation the odd product name carries
].join('')

/** Czech must be present or the protocol is broken — assert it explicitly. */
const CZECH = 'áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ'
/**
 * Regression guards for the exact strings that exposed the truncation bug:
 * German (Müsli, Jägermeister), Slovak (ľalia, ôsma), Polish.
 */
const GERMAN = 'äöüßÄÖÜ'
const SLOVAK = 'ľĺŕôäĽĹŔÔÄ'
const POLISH = 'łąćęńóśźżŁĄĆĘŃÓŚŹŻ'
const MUST_COVER = CZECH + GERMAN + SLOVAK + POLISH

const FACES = [
  { src: 'Roboto-Regular.ttf', out: 'Roboto-cs-regular.ttf', label: 'regular' },
  { src: 'Roboto-Bold.ttf', out: 'Roboto-cs-bold.ttf', label: 'bold' },
]

await mkdir(OUT, { recursive: true })

let failed = false
/** Characters every face renders. The app may only emit these. */
let supported = null

for (const face of FACES) {
  const original = await readFile(join(SRC, face.src))
  const subset = await subsetFont(original, REQUESTED, { targetFormat: 'truetype' })

  // jsPDF only accepts TrueType and gates on the magic bytes. If subset-font ever
  // returns OpenType/CFF, jsPDF rejects it at runtime with "No unicode cmap for font".
  const magic = subset.subarray(0, 4).toString('hex')
  if (magic !== '00010000') {
    console.error(`✗ ${face.out}: not TrueType (magic ${magic}) — jsPDF would reject this`)
    failed = true
    continue
  }

  // Read the cmap back rather than trusting REQUESTED: Roboto may not carry every
  // character we asked for, and the app must screen against what actually shipped.
  const font = createFont(subset)
  const present = new Set(
    [...REQUESTED].filter((ch) => font.hasGlyphForCodePoint(ch.codePointAt(0))),
  )

  const missingRequired = [...MUST_COVER].filter((ch) => !present.has(ch))
  if (missingRequired.length) {
    console.error(`✗ ${face.out}: missing required glyphs ${JSON.stringify(missingRequired)}`)
    failed = true
    continue
  }

  supported = supported ? new Set([...supported].filter((ch) => present.has(ch))) : present

  await writeFile(join(OUT, face.out), subset)
  const pct = ((1 - subset.length / original.length) * 100).toFixed(1)
  console.log(
    `✓ ${face.label.padEnd(8)} ${(original.length / 1024).toFixed(1)} kB → ` +
      `${face.out} ${(subset.length / 1024).toFixed(1)} kB (−${pct}%), ${present.size} glyphs`,
  )
}

if (failed || !supported) process.exit(1)

const chars = [...supported].sort((a, b) => a.codePointAt(0) - b.codePointAt(0)).join('')
await writeFile(
  CHARSET_JSON,
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/subset-font.mjs — do not edit. Characters the embedded ' +
        'PDF font can render. pdf.ts screens text against this; anything else would be ' +
        'silently dropped or would truncate the rest of the string.',
      chars,
    },
    null,
    2,
  ) + '\n',
)
console.log(`✓ charset.json: ${supported.size} characters renderable in every face`)
